[build]
  command = "npm ci && cd netlify/functions && npm ci && cd ../.. && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_USE_PRODUCTION = "false"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe", "@supabase/supabase-js"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
