[build]
  command = "npm ci && cd netlify/functions && npm ci && cd ../.. && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.17.0"
  # VITE_ variables are PUBLIC and meant to be in the browser bundle
  # These are NOT secrets - they are public API endpoints and keys
  SECRETS_SCAN_OMIT_KEYS = ["VITE_SUPABASE_URL", "VITE_SUPABASE_ANON_KEY", "VITE_STRIPE_PUBLISHABLE_KEY"]

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["stripe", "@supabase/supabase-js"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
